name: tests

# https://docs.github.com/de/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/using-workflows

on:
  push:
  pull_request:
  schedule:
    - cron: '37 3 * * *'

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.x"]
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [macos-latest]
        # exclude:

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install zbar shared lib for QReader (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libzbar0
      - name: Install zbar shared lib for QReader (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install zbar
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements-dev.txt
          pip install -U .
      - name: Test with pytest cv2 4.6
        run: |
          pip install --force-reinstall -v "opencv-contrib-python==4.6.0"
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_6_d0
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_6_f0
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_6_f1
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_7
          pytest -vvv -s tests/extract_otp_secrets_test.py
      - name: Test with pytest cv2 4.7
        run: |
          pip install --force-reinstall -v "opencv-contrib-python==4.7.0"
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_6_d0
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_6_f0
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_6_f1
          pytest -vvv -s tests/extract_otp_secrets_test.py::test_cv2_segfault_7
          pytest -vvv -s tests/extract_otp_secrets_test.py
